airflow:
  # Don't use this fernet key in production!
  fernet_key: "FCDPyxFGtznKUalt5XvF8UwA5YEXcV1VIi_D2sGVLtk="
  image:
    repository: airflow
    tag: latest
    pull_policy: IfNotPresent
  config:
  logs:
    persistence:
      existingClaim: nfs-airflow-logs
  dags:
    persistence:
      enabled: false  # Persistence must be disabled when using git-sync
    git:
      # Play around with different repositories, branches and subpaths
      # subpath is the relative directory path in the git repository where
      # the dags can be found.
      url: https://github.com/MiguelPeralvo/airflow-dags
      branch: master
      subpath: dags
      wait: 60
  rbac:
    enabled: false

ingress:
  enabled: false

postgresql:
  enabled: true
  postgresUser: postgres
  postgresPassword: airflow
  postgresDatabase: airflow
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
